# Generated by Django 4.0.2 on 2022-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='metrics',
            field=models.CharField(choices=[('Fahrenheit', 'Fahrenheit'), ('Celsius', 'Celsius'), ('Kelvin', 'Kelvin')], default='Fahrenheit', max_length=100),
        ),
    ]
