# Generated by Django 4.0.2 on 2022-04-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_history_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='metrics',
        ),
    ]
